### ISSUE TITLE
Crashes on server.

### ISSUE THREAD

**Issue by K0-RR** [Skylortrexler/Sentimentality-2#3]
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
[13:47:44] [main/WARN]: Error loading class: website/skylorbeck/sentimentality2/ItemEntityRotator (java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER)
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	... 9 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.server.Main.main(Main.java:87)
	... 14 more
Caused by: java.lang.RuntimeException: Cannot load class website.skylorbeck.sentimentality2.ItemEntityRotator in environment type SERVER
	at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:75)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_2246.<clinit>(class_2246.java:99)
	... 23 more

**Comment by skylorbeck** [comment]
Investigating now. Not sure why this is happening. I guess I never tested it on a real server, only the internal server you use for LAN hosting.

**Comment by skylorbeck** [comment]
Resolved in next update

**Comment by skylorbeck** [comment]
btw this one was a hydra. Solved six problems with this one ticket. Thanks.

**Comment by skylorbeck** [comment]
Also you might get some errors but it'll be fine for now. Working on those errors as we speak
